name: "Terraform"
on:
  push:
    branches:
  pull_request:

jobs:
  grep_changeset:
    name: "Grep change set"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          files: |
            *.tf
            *.tlp
            !*.md
            environments/**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  
  invoke-terrafom-workflow:
    strategy:
      matrix:
        changed_dir: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
    uses: ./.github/workflows/terraform.yml
    if: steps.changed-files-dir-names.outputs.any_changed == 'true'
    with:
      changed_dir: ${{ matrix.changed_dir }}
    
  
